#!/bin/bash
# =============================================================================
# Spack Installer — AIStack
# =============================================================================
# Usage:
#   cd /home/apps/AIStack
#   sudo bash install_spack.sh
#
# What this does:
#   1. Verifies git is installed
#   2. Clones Spack from GitHub into /home/apps/spack (skips if present)
#   3. Sources the Spack environment
#   4. Installs CUDA 13.0 via Spack using 10 parallel build jobs
# =============================================================================

set -o pipefail

AISTACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPACK_DIR="/home/apps/spack"
SPACK_ENV_SCRIPT="$SPACK_DIR/share/spack/setup-env.sh"
SPACK_GITHUB="https://github.com/spack/spack.git"
BUILD_JOBS=40
LOG_DIR="$AISTACK_DIR/logs"
SPACK_LOG="$LOG_DIR/spack_install.log"

mkdir -p "$LOG_DIR"

# ─── COLORS ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; RED='\033[0;31m'
YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

log()      { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$SPACK_LOG"; }
log_pass() { echo -e "  ${GREEN}✔${NC} $*" | tee -a "$SPACK_LOG"; }
log_skip() { echo -e "  ${YELLOW}⊘${NC} $*" | tee -a "$SPACK_LOG"; }
log_fail() { echo -e "  ${RED}✘${NC} $*" | tee -a "$SPACK_LOG"; }
die()      { echo -e "${RED}ERROR: $*${NC}" | tee -a "$SPACK_LOG"; exit 1; }

log "=== Spack Installer — $(date) ==="
log "Spack dir  : $SPACK_DIR"
log "CUDA       : 13.0"
log "Build jobs : $BUILD_JOBS"

# ─── STEP 1: Verify git ──────────────────────────────────────────────────────
log "=== STEP 1: Checking git ==="
if command -v git &>/dev/null; then
    GIT_VERSION=$(git --version)
    log_pass "git found: $GIT_VERSION"
else
    log "git not found — attempting install via dnf..."
    if command -v dnf &>/dev/null; then
        dnf install -y git >> "$SPACK_LOG" 2>&1 \
            && log_pass "git installed" \
            || die "git installation failed — check $SPACK_LOG"
    elif command -v apt-get &>/dev/null; then
        apt-get install -y git >> "$SPACK_LOG" 2>&1 \
            && log_pass "git installed" \
            || die "git installation failed — check $SPACK_LOG"
    else
        die "git not found and no supported package manager (dnf/apt). Install git manually."
    fi
fi

# ─── STEP 2: Install Spack ───────────────────────────────────────────────────
log "=== STEP 2: Installing Spack ==="
if [[ -d "$SPACK_DIR" && -f "$SPACK_ENV_SCRIPT" ]]; then
    log_skip "Spack already installed at $SPACK_DIR"
else
    log "Cloning Spack from GitHub..."
    if git clone --depth=1 "$SPACK_GITHUB" "$SPACK_DIR" >> "$SPACK_LOG" 2>&1; then
        log_pass "Spack cloned → $SPACK_DIR"
    else
        die "Failed to clone Spack — check $SPACK_LOG"
    fi
fi

# ─── STEP 3: Source Spack ────────────────────────────────────────────────────
log "=== STEP 3: Loading Spack environment ==="
if [[ ! -f "$SPACK_ENV_SCRIPT" ]]; then
    die "Spack setup script not found: $SPACK_ENV_SCRIPT"
fi

# shellcheck source=/dev/null
source "$SPACK_ENV_SCRIPT"

if command -v spack &>/dev/null; then
    SPACK_VERSION=$(spack --version)
    log_pass "Spack loaded: $SPACK_VERSION"
else
    die "Spack command not available after sourcing setup-env.sh"
fi

# ─── STEP 4: Install CUDA 13.0 ───────────────────────────────────────────────
log "=== STEP 4: Installing CUDA 13.0 (jobs=$BUILD_JOBS) ==="

# Check if already installed
if spack find cuda@13.0 &>/dev/null 2>&1; then
    log_skip "CUDA 13.0 already installed in Spack"
else
    log "Running: spack install -j$BUILD_JOBS cuda@13.0"
    if spack install -j$BUILD_JOBS cuda@13.0 2>&1 | tee -a "$SPACK_LOG"; then
        log_pass "CUDA 13.0 installed"
    else
        die "CUDA 13.0 installation failed — check $SPACK_LOG"
    fi
fi

# ─── STEP 5: Load CUDA and verify ────────────────────────────────────────────
log "=== STEP 5: Loading CUDA 13.0 ==="
spack load cuda@13.0

CUDA_HOME_DETECTED=$(spack location -i cuda@13.0 2>/dev/null)
if [[ -n "$CUDA_HOME_DETECTED" ]]; then
    export CUDA_HOME="$CUDA_HOME_DETECTED"
    log_pass "CUDA_HOME=$CUDA_HOME"
fi

if command -v nvcc &>/dev/null; then
    NVCC_VERSION=$(nvcc --version | grep "release" | awk '{print $6}' | tr -d ,)
    log_pass "nvcc available: $NVCC_VERSION"
else
    log_skip "nvcc not in PATH — load CUDA before compiling: spack load cuda@13.0"
fi

# ─── STEP 6: Persist Spack in shell init ─────────────────────────────────────
log "=== STEP 6: Writing Spack init to /etc/profile.d/spack.sh ==="
PROFILE_SCRIPT="/etc/profile.d/spack.sh"
if [[ -f "$PROFILE_SCRIPT" ]]; then
    log_skip "$PROFILE_SCRIPT already exists"
else
    cat > "$PROFILE_SCRIPT" << EOF
# Spack environment — auto-generated by AIStack install_spack.sh
export SPACK_ROOT=$SPACK_DIR
source \$SPACK_ROOT/share/spack/setup-env.sh
EOF
    log_pass "Written: $PROFILE_SCRIPT"
fi

# ─── SUMMARY ─────────────────────────────────────────────────────────────────
echo "" | tee -a "$SPACK_LOG"
echo -e "${BOLD}════════════════════════════════════════════════════════════${NC}" | tee -a "$SPACK_LOG"
echo -e "${BOLD}                      SPACK SUMMARY${NC}" | tee -a "$SPACK_LOG"
echo -e "${BOLD}════════════════════════════════════════════════════════════${NC}" | tee -a "$SPACK_LOG"
echo "" | tee -a "$SPACK_LOG"
echo    "  Spack root : $SPACK_DIR" | tee -a "$SPACK_LOG"
echo    "  CUDA       : 13.0" | tee -a "$SPACK_LOG"
[[ -n "$CUDA_HOME_DETECTED" ]] && \
echo    "  CUDA_HOME  : $CUDA_HOME_DETECTED" | tee -a "$SPACK_LOG"
echo    "  Log        : $SPACK_LOG" | tee -a "$SPACK_LOG"
echo "" | tee -a "$SPACK_LOG"
echo -e "${BOLD}  ── Quick reference ──${NC}" | tee -a "$SPACK_LOG"
echo    "    source $SPACK_ENV_SCRIPT    # load Spack in current shell" | tee -a "$SPACK_LOG"
echo    "    spack load cuda@13.0        # activate CUDA 13.0" | tee -a "$SPACK_LOG"
echo    "    spack find                  # list installed packages" | tee -a "$SPACK_LOG"
echo    "    spack info cuda             # show available CUDA versions" | tee -a "$SPACK_LOG"
echo "" | tee -a "$SPACK_LOG"
echo -e "${BOLD}════════════════════════════════════════════════════════════${NC}" | tee -a "$SPACK_LOG"